from pymongo import collection, MongoClient
from dotenv import load_dotenv
import os

load_dotenv()

client = MongoClient(os.getenv("MONGO_URI"))
db = client[os.getenv("DB_NAME")]
collection = db["advices"]

evil_advices = [
    {"category": "office", "text": "Reply all to that company-wide email."},
    {"category": "chat", "text": "Send 'k' as a reply."},
    {"category": "tech", "text": "Turn off autosave before a big project."},
    {"category": "windows", "text": "Delete system32 (don't actually)."},
    {"category": "productivity", "text": "Type without looking—always."},
    {"category": "office", "text": "Use your boss’s mug."},
    {"category": "library", "text": "Lick your fingers before turning pages."},
    {"category": "career", "text": "Submit your CV as a photo."},
    {"category": "communication", "text": "Always talk over people in meetings."},
    {"category": "security", "text": "Use the same password for everything."},
    {"category": "tech", "text": "Click all popups that say 'You won'."},
    {"category": "office", "text": "Use Comic Sans in your presentation."},
    {"category": "emails", "text": "Send emails without subject lines."},
    {"category": "social", "text": "Like your own posts immediately."},
    {"category": "career", "text": "Write 'ASAP' in all caps—every time."},
    {"category": "zoom", "text": "Join meetings with mic and camera on by default."},
    {"category": "food", "text": "Microwave fish in the office."},
    {"category": "meetings", "text": "Always ask 'Can you repeat that?' at the end."},
    {"category": "office", "text": "Leave your phone on loud in meetings."},
    {"category": "coding", "text": "Push to production on Fridays."},
    {"category": "coding", "text": "Write all code in one file."},
    {"category": "coding", "text": "Hardcode your credentials."},
    {"category": "relationships", "text": "Reply 'seen' and never respond."},
    {"category": "personal", "text": "Borrow pens and never return them."},
    {"category": "tech", "text": "Download RAM from suspicious sites."},
    {"category": "gaming", "text": "Teabag every downed opponent."},
    {"category": "style", "text": "Wear sunglasses indoors."},
    {"category": "etiquette", "text": "Stand too close in queues."},
    {"category": "drama", "text": "Start group chats just to leave them."},
    {"category": "texting", "text": "Use all caps for everything."},
    {"category": "dating", "text": "Text 'wyd' at 2AM to your ex."},
    {"category": "office", "text": "Eat loudly during Zoom calls."},
    {"category": "social", "text": "Unsend messages after they're seen."},
    {"category": "parking", "text": "Take up two spots."},
    {"category": "coding", "text": "Name variables like `x`, `y`, `z`."},
    {"category": "email", "text": "Use Reply All to say 'Thanks'."},
    {"category": "security", "text": "Write passwords on sticky notes."},
    {"category": "presentation", "text": "Read slides word for word."},
    {"category": "group work", "text": "Wait till the last day to contribute."},
    {"category": "boss", "text": "Call your boss by their first name uninvited."},
        {"category": "tech", "text": "Force shutdown your PC to save time."},
    {"category": "coding", "text": "Comment every line with 'self-explanatory'."},
    {"category": "office", "text": "Take phone calls on speaker in open office."},
    {"category": "career", "text": "Lie on your resume. YOLO."},
    {"category": "emails", "text": "Use Comic Sans in your email signature."},
    {"category": "security", "text": "Post your password hints on your bio."},
    {"category": "communication", "text": "Start emails with 'Hey you'."},
    {"category": "social", "text": "Tag everyone you know in memes."},
    {"category": "relationships", "text": "Announce breakups via story posts."},
    {"category": "productivity", "text": "Take breaks every 5 minutes."},
    {"category": "windows", "text": "Alt+F4 speeds up your browser."},
    {"category": "etiquette", "text": "Eat chips during phone calls."},
    {"category": "presentation", "text": "Use red text on green backgrounds."},
    {"category": "zoom", "text": "Eat cereal loudly with your mic on."},
    {"category": "texting", "text": "Reply with just emojis to serious texts."},
    {"category": "dating", "text": "Ask ‘u up?’ to everyone at 1AM."},
    {"category": "group work", "text": "Let others start, then criticize late."},
    {"category": "teamwork", "text": "Take credit for others' work subtly."},
    {"category": "gaming", "text": "Yell at teammates with your mic on."},
    {"category": "library", "text": "Play TikTok on full volume."},
    {"category": "personal", "text": "Set 20 alarms and snooze all."},
    {"category": "style", "text": "Wear Crocs to a job interview."},
    {"category": "email", "text": "Use bright yellow highlight for everything."},
    {"category": "productivity", "text": "Use 20 tabs instead of bookmarks."},
    {"category": "coding", "text": "Use tabs and spaces randomly."},
    {"category": "security", "text": "Never log out of public PCs."},
    {"category": "office", "text": "Leave crumbs in shared keyboards."},
    {"category": "etiquette", "text": "Chew gum loudly during meetings."},
    {"category": "tech", "text": "Never update your software—ever."},
    {"category": "social", "text": "Comment 'first' on every post."},
    {"category": "career", "text": "Apply to jobs with 'pls hire me'."},
    {"category": "email", "text": "Write emails in ALL CAPS to show urgency."},
    {"category": "drama", "text": "Start rumors to spice things up."},
    {"category": "relationships", "text": "Send 'u miss me?' to 3 people at once."},
    {"category": "meetings", "text": "Interrupt with unrelated stories."},
    {"category": "communication", "text": "Reply 'k' to every long message."},
    {"category": "zoom", "text": "Do chores with your camera on."},
    {"category": "texting", "text": "Send voice notes for everything."},
    {"category": "parking", "text": "Park diagonally to protect your car."},
    {"category": "email", "text": "CC random people for transparency."},
    {"category": "boss", "text": "Use memes in status updates."},
    {"category": "tech", "text": "Install 10 antivirus tools at once."},
    {"category": "productivity", "text": "Skip planning, trust your vibe."},
    {"category": "coding", "text": "Write all logic in one huge function."},
    {"category": "office", "text": "Print memes on the company printer."},
    {"category": "gaming", "text": "Taunt your opponent after every kill."},
    {"category": "communication", "text": "Use 'per my last email' passive-aggressively."},
    {"category": "career", "text": "Turn interviews into therapy sessions."},
    {"category": "zoom", "text": "Screen share your personal tabs."},
    {"category": "style", "text": "Match neon colors for attention."},
    {"category": "relationships", "text": "Post cryptic quotes as indirects."},
    {"category": "food", "text": "Bring tuna to shared office fridge."},
    {"category": "personal", "text": "Ask strangers for phone chargers."},
    {"category": "security", "text": "Set your password to 'password'."},
    {"category": "drama", "text": "Like your ex's new partner's photos."},
    {"category": "texting", "text": "Send 15 messages instead of 1."},
    {"category": "emails", "text": "Reply to threads with unrelated thoughts."},
    {"category": "zoom", "text": "Use voice changer filters."},
    {"category": "coding", "text": "Comment code in all caps only."},
    {"category": "meetings", "text": "Always show up 15 mins late."},
    {"category": "boss", "text": "Send memes instead of reports."},
    {"category": "etiquette", "text": "Burp loudly and say ‘oops’."},
    {"category": "email", "text": "Use bright pink for your fonts."},
    {"category": "office", "text": "Announce breaks out loud."},
    {"category": "tech", "text": "Turn off antivirus—it slows you down."},
    {"category": "productivity", "text": "Multitask with 5 movies playing."},
    {"category": "relationships", "text": "Use your partner’s toothbrush."},
    {"category": "library", "text": "Watch YouTube without headphones."},
    {"category": "zoom", "text": "Host while driving."},
    {"category": "career", "text": "Use Instagram DMs to apply for jobs."},
    {"category": "emails", "text": "Add everyone to the 'To' field always."},
    {"category": "texting", "text": "Send full essays as messages."},
    {"category": "communication", "text": "Use 'lol' after every sentence."},
    {"category": "food", "text": "Steal fries from coworkers' plates."},
    {"category": "boss", "text": "Ask for a raise on Mondays."},
    {"category": "style", "text": "Wear pajamas to work meetings."},
    {"category": "group work", "text": "Send files right before the deadline."},
    {"category": "security", "text": "Write your ATM pin on your card."},
    {"category": "productivity", "text": "Keep 30 Chrome tabs open."},
    {"category": "gaming", "text": "Rage quit and blame lag."},
    {"category": "email", "text": "Reply with GIFs only."},
    {"category": "communication", "text": "End every message with 'period'."},
    {"category": "social", "text": "Go live at random times."},
    {"category": "tech", "text": "Install toolbars for 'better search'."},
    {"category": "coding", "text": "Don't use version control—YOLO!"}
]


existing_texts = set(doc["text"] for doc in collection.find({}, {"text": 1}))
new_advices = [advices for advice in evil_advices if advice["text"] not in existing_texts]

if new_advices:
    collection.insert_many(new_advices)
    print(f"✅ Inserted {len(new_advices)} new advices.")
else:
    print("⚠️ No new advices to insert.")